version: '3***REMOVED***3'
services:
  # SERVER
  test_unicloud_server:
    image: agarbato1/unison-unicloud:ha
    ports:
      - "2222:22"
      - "5000:80"
    environment:
      - USER=unison
      - USERID=1000
      - SERVER_HOSTNAME=unicloud_testing_server
      - SERVER_UI_USERNAME=admin
      - SERVER_UI_PASSWORD=abcd12345
      - SERVER_DEBUG=True
      - ROLE=SERVER
      - HOME_ASSISTANT=True
      - HOME_ASSISTANT_URL=https://home***REMOVED***donidoni***REMOVED***it
      - HOME_ASSISTANT_PUSH_INTERVAL=15
      - HOME_ASSISTANT_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9***REMOVED***eyJpc3MiOiIzMWI4ODRjMzc1M2Q0OWJlOWEzNDUzNzVjZGNjOTY1NiIsImlhdCI6MTYyNzgzNzk3MCwiZXhwIjoxOTQzMTk3OTcwfQ***REMOVED***shBHbGPXda7HvH_BzhGqQ6ABC4BoTqTOZ0Kx7PCl5Fk
    networks:
      unison:
        aliases:
          - unicloud_server
    volumes:
      - type: bind
        source: ***REMOVED***/local_tests/server
        target: /data
      - type: bind
        source: ***REMOVED***/local_tests/server/shares
        target: /shares
  # CLIENT
  test_unicloud_client:
    image: agarbato1/unison-unicloud:ha
    environment:
      - CLIENT_HOSTNAME=testing-client1
      - ROLE=CLIENT
      - USER=unison
      - USERID=1000
      - SERVER_HOSTNAME=unicloud_server
      - SERVER_PORT=22
      - SERVER_SHARE=share1
      - SHARE_IGNORE=***REMOVED***git*|***REMOVED***idea|***REMOVED***unison|***REMOVED***DS_Store
      - API_PROTOCOL=http
      - API_PORT=80
      - SYNC_INTERVAL=60
    restart: on-failure
    volumes:
      - type: bind
        source: ***REMOVED***/local_tests/client
        target: /data
      - type: bind
        source: ***REMOVED***/local_tests/client/share
        target: /data/share
    networks:
      unison:

networks:
  unison:
    driver: bridge
    ipam:
      driver: default
