client_hostname = '{{ client_hostname }}'
role = '{{ role }}'
user = '{{ user }}'
user_uid = '{{ user_uid }}'
server_hostname = '{{ server_hostname }}'
server_share = '{{ server_share }}'
share_ignore = '{{ share_ignore }}'
unison_params = '{{ unison_params }}'
sync_interval = '{{ sync_interval }}'
server_api_port = '{{ server_api_port }}'
server_api_protocol = '{{ server_api_protocol }}'

